config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :groups do
    member do
      get :join
      get :leave
    end
  end
  
  resources :users
  resources :chats do
    collection do
      post :save_message
      get :group_messages
    end
  end

  root 'groups#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  #Associations
  has_and_belongs_to_many :users
end

app/models/message.rb
class Message
  def initialize(content, sender_id, recipient_id)
  	@content = content
  	@sender_id = sender_id
  	@recipient_id = recipient_id
  end

  def save
    $redis.sadd "group:#{ @recipient_id }", self.to_json
  end

  def find_by_group_id(id)
    $redis.smembers "group:{ id }"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Associations
  has_and_belongs_to_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  realtime_controller({:queue => :redis})

  def realtime_user_id
    current_user.id if current_user
  end

  def realtime_server_url
    return 'http://0.0.0.0:5001'
  end

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
      devise_parameter_sanitizer.for(:account_update) << :name
    end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def save_message
    @group = Group.find_by_id(params[:recipient_id])
    @sender = User.find_by_id(params[:sender_id]);
    @message = Message.new(params[:content], params[:sender_id], params[:recipient_id])
    @message.save
    
    pub_msg = { content: params[:content], sender: @sender.name }
    $redis.publish 'realtime_msg', { msg: pub_msg, recipient_user_ids: @group.users.collect(&:id)}.to_json
    render json: @message.to_json
  end

  def show
    messages = $redis.smembers "group:#{params[:id]}"
    resp = messages.map do |m| 
      jm = JSON.parse(m);
      sender = User.find_by_id(jm['sender_id'])
      { content: jm['content'], sender: sender.name }
    end
    render json: resp.to_json
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  
  def index
  	@groups = Group.all
  end

  def new
  	@group = Group.new
  end

  def create
  	@group = Group.new(permitted_params)

  	if @group.save
  		respond_to do |format|
  			format.html { redirect_to groups_path }
  			format.json { render json: group }
  		end
  	else
  		respond_to do |formate|
  			format.html { render :new }
  			format.json { render json: @group.errors }
  		end
  	end

  end

  def edit
  	@group = Group.find_by_id(params[:id])
  end

  def update
  	@group = Group.new(permitted_params)

  	if @group.save
  		respond_to do |format|
  			format.html { redirect_to groups_path }
  			format.json { render json: @group }
  		end
  	else
  		respond_to do |formate|
  			format.html { render :new }
  			format.json { render json: @group.errors }
  		end
  	end
  end

  def show
    @group = Group.find_by_id(params[:id])
  end

  def join
    @group = Group.find_by_id(params[:id])
    @group.users << current_user
    flash[:notice] = "You have joined group #{@group.name}. Start chatting with your friends"
    redirect_to group_path(@group)
  end

  def leave
    @group = Group.find_by_id(params[:id])
    @group.users.delete current_user
    flash[:notice] = "You have leaved group #{@group.name}. Start chatting with your friends"
    redirect_to groups_path
  end

  private
    def permitted_params
    	params.require(:group).permit(:name, user_ids: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!
  
	def index
		@users = User.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.haml
= form_for(@group, html: { class: 'form-horizontal'}) do |f|
  - if @group.errors.any?
    #error_explanation
      %h2= "#{pluralize(@group.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg

  %div.form-group
    = f.label :name,"Name", :class => 'col-lg-2 control-label'
    %abbr{title: "required"} *
    %div.col-lg-7
      = f.text_field :name, :class => 'form-control', placeholder: "Name"
  %div.form-group
    = f.label :name,"Select Group Users", :class => 'col-lg-2 control-label'
    %abbr{title: "required"} *
    %div.col-lg-7
      = f.collection_select(:user_ids, User.all, :id, :name, {}, { multiple: true, prompt: true, class: 'form-control'} )
  %div.form-group
    %div.col-lg-10.col-lg-offset-2
      = link_to "Back", groups_path, :class => 'btn btn-default'
      = f.button :submit, :class => 'btn btn-primary'

app/views/groups/edit.haml
%h1 Editing Group
.row
  .well
    = render 'form'

app/views/groups/index.haml
.clearfix
  %h1.pull-left Listing Group
  %a.btn.btn-large.btn-primary.pull-right.create-action{:href => "#{new_group_path}", :title => "Create Group"} + Create Group

- if @groups.empty?
  %p.text-center
    No record to show
- else
  %table.table
    %tr
      %th #
      %th Name
      %th Friends within group
      %th Actions
    - @groups.each_with_index do |group, index|
      %tr
        %td= index + 1

        %td= link_to group.name
        %td= group.users.collect(&:name).join(", ")
        %td
          - if(group.user_ids.include? current_user.id)
            = link_to 'Chat with Friends', group_path(group) 
            | 
            = link_to 'Leave Group', leave_group_path(group) 
          - else
            = link_to 'Join Group', join_group_path(group)

app/views/groups/new.haml
%h1 Creating Group
.row
  .well
    = render 'form'

app/views/groups/show.haml
.col-lg-6
  #chatwindow{'ng-controller'=>'ChatController', 'ng-init'=>"init(#{current_user.to_json}, #{@group.to_json})"}
    .titleBox
      = @group.name
    #messagewindow
      %ul.chat
        %li{ 'ng-repeat'=>'msg in messages' }
          %p
            {{ msg.sender }}: {{ msg.content }}
    %form.sendWindow{ :name => 'form', 'ng-submit'=>'sendMessage()', 'novalidate'=>'' }
      .input-group
        %input.form-control{ :placeholder => "Type Message", :type => "text", :name => 'message', 'ng-model'=>'message', 'ng-required'=>'true' }
        %span.input-group-btn
          %input.btn.btn-default{ :type=>'submit', :value=>'Send!', 'ng-disabled'=>'chat.$invalid' }

app/views/layouts/_footer.html.haml
%footer
  %p &copy; ChatApp 2015

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %a.navbar-brand(href="#") ChatApp
      %button.navbar-toggle(data-target=".nav-responsive-collapse" data-toggle="collapse")
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .navbar-collapse.collapse.navbar-responsive-collapse
      = render "layouts/navigation"

app/views/layouts/_navigation.html.haml
- if user_signed_in?
  %ul.nav.navbar-nav
    %li
      = link_to "Groups", groups_path
    %li
      = link_to "Users", users_path

%ul.nav.navbar-nav.navbar-right
  - if user_signed_in?
    %li.dropdown
      %a{ :href => "#", title: "Options", :class => "dropdown-toggle", "data-toggle" => "dropdown" }
        %Strong
          Options
        %b.caret
      %ul.dropdown-menu
        %li
          = link_to 'Account Settings', edit_user_registration_path
        %li.divider
        %li
          = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path

app/views/layouts/application.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "ChatApp"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = realtime_support
    =# realtime_message_console_logger


  %body{ 'ng-app'=>"chatApp" }
    = render "layouts/header"

    #app.container

      .row
        .col-lg-12
          = bootstrap_flash
          = yield

      = render "layouts/footer"

app/views/users/index.haml
.clearfix
  %h1.pull-left Listing Users
  %a.btn.btn-large.btn-primary.pull-right.create-action{:href => "#{}", :title => "Create "} + Create

- if @users.empty?
  %p.text-center
    No record to show
- else
  %table.table
    %tr
      %th #
      %th Name
    - @users.each_with_index do |user, index|
      %tr
        %td= index + 1

        %td= user.name